"""empty message

Revision ID: 5e29f5d6540b
Revises: d1cb91ff9138
Create Date: 2020-12-28 01:35:31.908311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e29f5d6540b'
down_revision = 'd1cb91ff9138'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'matches', ['name'])
    op.create_unique_constraint(None, 'photos', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photos', type_='unique')
    op.drop_constraint(None, 'matches', type_='unique')
    # ### end Alembic commands ###
